pipeline {
    // master executor should be set to 0
    agent any
    stages {
        stage('Build Assembly') {
            steps {
                //sh for mac or linux, bat for windows
                bat "dotnet build"
                bat "dotnet restore"
            }
        }
        stage('Build Image') {
            steps {
                script {
                    app = docker.build('ramociocea/selenium-docker', './umpg-contracts-web-test-automation-main')
                }
            }
        }
        stage('Push Image') {
            steps {
			    script{
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub'){
                        app.push("${BUILD_NUMBER}")
			            app.push("latest")
                    }            
                }                        
            }
        }
    }
}