pipeline {
    // master executor should be set to 0
    agent any
    stages {
        stage('Build Assembly') {
            steps {
                //sh for mac or linux, bat for windows
                bat "dotnet build"
                bat "dotnet restore"
            }
        }
        stage('Build Image') {
            steps {
                //sh
                bat "docker build -t='ramociocea/selenium-docker' ."
            }
        }
        stage('Push Image') {
            steps {
			    withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'pass', usernameVariable: 'user')]) {
                    //sh
			        bat "docker login --username=${user} --password=${pass}"
			        bat "docker push ramodocker/selenium-docker:latest"
			    }                           
            }
        }
    }
}